#cloud-config
# Update the packages
package_update: true
package_upgrade: true
# Get relevant packages
packages:
  - wget
  - curl
# Run important commands - Create a random password and a SQLRoot user & install php, sql server+client
runcmd:
- apt install mariadb-server mariadb-client -y
- pw=$(openssl rand -base64 18); mysqladmin -u root -h localhost password "$pw"; echo "Password=$pw" >> /home/mysql_access.txt
- mysqladmin reload

# Create database for Wordpress
- sudo mysql -e "CREATE DATABASE wordpress;"
- pw1=$(openssl rand -base64 18); sudo mysql -e "CREATE USER 'wp-admin'@'%' IDENTIFIED BY '$pw1'; GRANT ALL PRIVILEGES ON wordpress.* TO 'root'@'%' WITH GRANT OPTION;"; echo "Password=$pw" >> /home/wp-admin_access.txt
- mysqladmin reload

# Bind auf 0.0.0.0
- sudo rm /etc/mysql/mariadb.conf.d/50-server.cnf
- sudo wget -P /etc/mysql/mariadb.conf.d/ https://raw.githubusercontent.com/GBSSGMG/M346-CMS-Wordpress/main/Installation/Configs/50-server.cnf -O50-server.cnf