#cloud-config
# Update the packages
package_update: true
package_upgrade: true
# Get relevant packages
packages:
  - wget
  - curl
# Run important commands - Create a random password and a SQLRoot user & install php, sql server+client
runcmd:
- apt install mariadb-server mariadb-client -y
- pw=$(openssl rand -base64 18); mysqladmin -u root -h localhost password "$pw"; echo "mysql_password=$pw" >> /home/mysql_access.txt
- mysqladmin reload

# Create database for Wordpress
- sudo mysql -e "CREATE DATABASE wordpress;"